name: turborepo affected packages
description: turborepo affected packages
inputs:
  turbo-config-file:
    description: "Turbo configuration file"
    required: false
  packages-or-tasks-yaml:
    description: "YAML configuration for packages or tasks dependencies"
    required: false

outputs:
  affected-packages:
    description: "Affected package names."
  affected-tasks:
    description: "Affected task names."

branding:
  icon: git-pull-request
  color: blue

runs:
  using: node20
  main: "./dist/index.js"
